package filesystem

import (
	"io"
	"os"
	"strings"
)

func CopyFile(src, dst string) error {
	if strings.HasSuffix(src, ".go") {
		return CopyGoSourceFile(src, dst)
	} else {
		sf, err := os.Open(src)
		if err != nil {
			return err
		}
		defer sf.Close()
		_, err = os.Stat(dst)
		if err == nil {
			return os.ErrExist
		}
		df, err := os.Create(dst)
		if err != nil {
			return err
		}
		defer df.Close()
		_, err = io.Copy(df, sf)
		return err
	}
}

func CopyGoSourceFile(src, dst string) error {
	sf, err := os.Open(src)
	if err != nil {
		return err
	}
	defer sf.Close()
	_, err = os.Stat(dst)
	if err == nil {
		return os.ErrExist
	}
	df, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer df.Close()
	_, err = df.WriteString(`// Code generated by "Kaiju build system"; DO NOT EDIT.
`)
	if err != nil {
		return err
	}
	_, err = io.Copy(df, sf)
	return err
}
