/******************************************************************************/
/* narrow_phase.go                                                            */
/******************************************************************************/
/* MIT License, Copyright (c) 2015-present Brent Farris, (John 4:13-14)       */
/******************************************************************************/

package graviton

import (
	"sync"

	"kaijuengine.com/klib"
	"kaijuengine.com/matrix"
	"kaijuengine.com/platform/concurrent"
)

const (
	contactEpsilon       matrix.Float = 0.00001
	narrowMinPairsPerJob              = 64
	maxManifoldContacts               = 4
)

// Contact contains one world-space contact point generated by the narrow phase.
// Normal always points from BodyA toward BodyB.
type Contact struct {
	BodyA       *RigidBody
	BodyB       *RigidBody
	Point       matrix.Vec3
	PointA      matrix.Vec3
	PointB      matrix.Vec3
	Normal      matrix.Vec3
	Penetration matrix.Float
}

// ContactManifold groups contacts for a colliding body pair.
type ContactManifold struct {
	BodyA    *RigidBody
	BodyB    *RigidBody
	Normal   matrix.Vec3
	Contacts [maxManifoldContacts]Contact
	Count    int
}

func (m *ContactManifold) add(contact Contact) {
	if m.Count >= len(m.Contacts) {
		return
	}
	m.Contacts[m.Count] = contact
	m.Count++
}

// NarrowPhase performs exact pair tests after the broad phase has produced
// candidate pairs. It owns reusable buffers so a physics step can run without
// per-pair allocations.
type NarrowPhase struct {
	manifolds []ContactManifold
	buffers   [][]ContactManifold
}

func (n *NarrowPhase) Reset() {
	n.manifolds = n.manifolds[:0]
	for i := range n.buffers {
		n.buffers[i] = n.buffers[i][:0]
	}
}

func (n *NarrowPhase) Manifolds() []ContactManifold {
	return n.manifolds
}

func (n *NarrowPhase) Collide(pairs []ActivePair, threads *concurrent.Threads) []ContactManifold {
	n.Reset()
	if len(pairs) == 0 {
		return n.manifolds
	}
	workers := broadPhaseWorkerCount(threads, len(pairs), narrowMinPairsPerJob)
	if workers == 1 {
		n.collideRange(pairs, 0, len(pairs), &n.manifolds)
		return n.manifolds
	}
	n.ensureBuffers(workers)
	runNarrowPhaseJobs(threads, workers, len(pairs), func(start, end, worker int) {
		buffer := n.buffers[worker][:0]
		n.collideRange(pairs, start, end, &buffer)
		n.buffers[worker] = buffer
	})
	total := 0
	for i := range workers {
		total += len(n.buffers[i])
	}
	if cap(n.manifolds) < total {
		n.manifolds = make([]ContactManifold, 0, total)
	}
	for i := range workers {
		n.manifolds = append(n.manifolds, n.buffers[i]...)
	}
	return n.manifolds
}

func (n *NarrowPhase) collideRange(pairs []ActivePair, start, end int, manifolds *[]ContactManifold) {
	for i := start; i < end; i++ {
		pair := pairs[i]
		if pair.BodyA == nil || pair.BodyB == nil {
			continue
		}
		manifold, ok := CollideBodies(pair.BodyA, pair.BodyB)
		if ok {
			*manifolds = append(*manifolds, manifold)
		}
	}
}

func (n *NarrowPhase) ensureBuffers(count int) {
	for len(n.buffers) < count {
		n.buffers = append(n.buffers, make([]ContactManifold, 0, 64))
	}
}

func runNarrowPhaseJobs(threads *concurrent.Threads, workers, items int, work func(start, end, worker int)) {
	jobs := make([]func(int), workers)
	wg := sync.WaitGroup{}
	wg.Add(workers)
	for worker := range workers {
		start := worker * items / workers
		end := (worker + 1) * items / workers
		worker := worker
		jobs[worker] = func(int) {
			defer wg.Done()
			work(start, end, worker)
		}
	}
	threads.AddWork(jobs)
	wg.Wait()
}

func CollideBodies(a, b *RigidBody) (ContactManifold, bool) {
	if a == nil || b == nil {
		return ContactManifold{}, false
	}
	if contact, ok := collideBodyMeshPair(a, b); ok {
		contact.BodyA = a
		contact.BodyB = b
		manifold := ContactManifold{
			BodyA:  a,
			BodyB:  b,
			Normal: contact.Normal,
		}
		manifold.add(contact)
		return manifold, true
	}
	if contact, ok := collideBodyTerrainPair(a, b); ok {
		contact.BodyA = a
		contact.BodyB = b
		manifold := ContactManifold{
			BodyA:  a,
			BodyB:  b,
			Normal: contact.Normal,
		}
		manifold.add(contact)
		return manifold, true
	}
	shapeA := worldShape(a)
	shapeB := worldShape(b)
	contact, ok := collideShapes(shapeA, shapeB)
	if !ok {
		return ContactManifold{}, false
	}
	contact.BodyA = a
	contact.BodyB = b
	manifold := ContactManifold{
		BodyA:  a,
		BodyB:  b,
		Normal: contact.Normal,
	}
	manifold.add(contact)
	return manifold, true
}

func collideBodyMeshPair(a, b *RigidBody) (Contact, bool) {
	if a.Collision.Shape.Type == ShapeTypeMesh || b.Collision.Shape.Type == ShapeTypeMesh {
		if a.Collision.Shape.Type == ShapeTypeMesh && b.Collision.Shape.Type == ShapeTypeMesh {
			return Contact{}, false
		}
		if a.Collision.Shape.Type == ShapeTypeMesh {
			if !a.IsStatic() || a.Collision.Mesh == nil {
				return Contact{}, false
			}
			contact, ok := collidePrimitiveStaticMesh(worldShape(b), a.Collision.Mesh, &a.Transform)
			return flipContact(contact), ok
		}
		if !b.IsStatic() || b.Collision.Mesh == nil {
			return Contact{}, false
		}
		return collidePrimitiveStaticMesh(worldShape(a), b.Collision.Mesh, &b.Transform)
	}
	return Contact{}, false
}

func collideBodyTerrainPair(a, b *RigidBody) (Contact, bool) {
	if a.Collision.Shape.Type == ShapeTypeTerrain || b.Collision.Shape.Type == ShapeTypeTerrain {
		if a.Collision.Shape.Type == ShapeTypeTerrain && b.Collision.Shape.Type == ShapeTypeTerrain {
			return Contact{}, false
		}
		if a.Collision.Shape.Type == ShapeTypeTerrain {
			if !a.IsStatic() || a.Collision.Terrain == nil {
				return Contact{}, false
			}
			contact, ok := collidePrimitiveStaticTerrain(worldShape(b), a.Collision.Terrain, &a.Transform)
			return flipContact(contact), ok
		}
		if !b.IsStatic() || b.Collision.Terrain == nil {
			return Contact{}, false
		}
		return collidePrimitiveStaticTerrain(worldShape(a), b.Collision.Terrain, &b.Transform)
	}
	return Contact{}, false
}

func collideShapes(a, b Shape) (Contact, bool) {
	switch a.Type {
	case ShapeTypeSphere:
		return collideSphereAny(Sphere(a), b)
	case ShapeTypeAABB:
		return collideAABBAny(AABB(a), b)
	case ShapeTypeOOBB:
		return collideOOBBAny(OOBB(a), b)
	case ShapeTypeCapsule:
		return collideCapsuleAny(Capsule(a), b)
	case ShapeTypeCylinder:
		return collideCylinderAny(Cylinder(a), b)
	case ShapeTypeCone:
		return collideConeAny(Cone(a), b)
	default:
		return Contact{}, false
	}
}

func collideSphereAny(a Sphere, b Shape) (Contact, bool) {
	switch b.Type {
	case ShapeTypeSphere:
		return collideSphereSphere(a, Sphere(b))
	case ShapeTypeAABB:
		return collideSphereAABB(a, AABB(b))
	case ShapeTypeOOBB:
		return collideSphereOOBB(a, OOBB(b))
	case ShapeTypeCapsule:
		c, ok := collideSphereCapsule(a, Capsule(b))
		return c, ok
	case ShapeTypeCylinder:
		return collideSphereCylinder(a, Cylinder(b))
	case ShapeTypeCone:
		return collideSphereCone(a, Cone(b))
	default:
		return Contact{}, false
	}
}

func collideAABBAny(a AABB, b Shape) (Contact, bool) {
	switch b.Type {
	case ShapeTypeSphere:
		c, ok := collideSphereAABB(Sphere(b), a)
		return flipContact(c), ok
	case ShapeTypeAABB:
		return collideAABBAABB(a, AABB(b))
	case ShapeTypeOOBB:
		return collideOOBBOOBB(OOBBFromAABB(a), OOBB(b))
	case ShapeTypeCapsule:
		c, ok := collideCapsuleAABB(Capsule(b), a)
		return flipContact(c), ok
	case ShapeTypeCylinder:
		c, ok := collideCylinderOOBB(Cylinder(b), OOBBFromAABB(a))
		return flipContact(c), ok
	case ShapeTypeCone:
		c, ok := collideConeOOBB(Cone(b), OOBBFromAABB(a))
		return flipContact(c), ok
	default:
		return Contact{}, false
	}
}

func collideOOBBAny(a OOBB, b Shape) (Contact, bool) {
	switch b.Type {
	case ShapeTypeSphere:
		c, ok := collideSphereOOBB(Sphere(b), a)
		return flipContact(c), ok
	case ShapeTypeAABB:
		c, ok := collideOOBBOOBB(a, OOBBFromAABB(AABB(b)))
		return c, ok
	case ShapeTypeOOBB:
		return collideOOBBOOBB(a, OOBB(b))
	case ShapeTypeCapsule:
		c, ok := collideCapsuleOOBB(Capsule(b), a)
		return flipContact(c), ok
	case ShapeTypeCylinder:
		c, ok := collideCylinderOOBB(Cylinder(b), a)
		return flipContact(c), ok
	case ShapeTypeCone:
		c, ok := collideConeOOBB(Cone(b), a)
		return flipContact(c), ok
	default:
		return Contact{}, false
	}
}

func collideCapsuleAny(a Capsule, b Shape) (Contact, bool) {
	switch b.Type {
	case ShapeTypeSphere:
		c, ok := collideSphereCapsule(Sphere(b), a)
		return flipContact(c), ok
	case ShapeTypeAABB:
		return collideCapsuleAABB(a, AABB(b))
	case ShapeTypeOOBB:
		return collideCapsuleOOBB(a, OOBB(b))
	case ShapeTypeCapsule:
		return collideCapsuleCapsule(a, Capsule(b))
	case ShapeTypeCylinder:
		if !a.IntersectsCylinder(Cylinder(b)) {
			return Contact{}, false
		}
	case ShapeTypeCone:
		if !a.IntersectsCone(Cone(b)) {
			return Contact{}, false
		}
	default:
		return Contact{}, false
	}
	return approximateContact(Shape(a), b), true
}

func collideCylinderAny(a Cylinder, b Shape) (Contact, bool) {
	switch b.Type {
	case ShapeTypeSphere:
		c, ok := collideSphereCylinder(Sphere(b), a)
		return flipContact(c), ok
	case ShapeTypeAABB:
		return collideCylinderOOBB(a, OOBBFromAABB(AABB(b)))
	case ShapeTypeOOBB:
		return collideCylinderOOBB(a, OOBB(b))
	case ShapeTypeCapsule:
		c, ok := collideCapsuleAny(Capsule(b), Shape(a))
		return flipContact(c), ok
	case ShapeTypeCylinder:
		if !a.IntersectsCylinder(Cylinder(b)) {
			return Contact{}, false
		}
	case ShapeTypeCone:
		if !a.IntersectsCone(Cone(b)) {
			return Contact{}, false
		}
	default:
		return Contact{}, false
	}
	return approximateContact(Shape(a), b), true
}

func collideConeAny(a Cone, b Shape) (Contact, bool) {
	switch b.Type {
	case ShapeTypeSphere:
		c, ok := collideSphereCone(Sphere(b), a)
		return flipContact(c), ok
	case ShapeTypeAABB:
		return collideConeOOBB(a, OOBBFromAABB(AABB(b)))
	case ShapeTypeOOBB:
		return collideConeOOBB(a, OOBB(b))
	case ShapeTypeCapsule:
		c, ok := collideCapsuleAny(Capsule(b), Shape(a))
		return flipContact(c), ok
	case ShapeTypeCylinder:
		c, ok := collideCylinderAny(Cylinder(b), Shape(a))
		return flipContact(c), ok
	case ShapeTypeCone:
		if !a.IntersectCone(Cone(b)) {
			return Contact{}, false
		}
	default:
		return Contact{}, false
	}
	return approximateContact(Shape(a), b), true
}

func collidePrimitiveStaticMesh(primitive Shape, mesh *MeshCollision, meshTransform *matrix.Transform) (Contact, bool) {
	switch primitive.Type {
	case ShapeTypeSphere:
		return collideSphereMesh(Sphere(primitive), mesh, meshTransform)
	case ShapeTypeCapsule:
		return collideCapsuleMesh(Capsule(primitive), mesh, meshTransform)
	case ShapeTypeOOBB:
		return collideOOBBMesh(OOBB(primitive), mesh, meshTransform)
	default:
		return Contact{}, false
	}
}

func collidePrimitiveStaticTerrain(primitive Shape, terrain *TerrainCollision, terrainTransform *matrix.Transform) (Contact, bool) {
	if terrain == nil || !terrain.valid() {
		return Contact{}, false
	}
	queryBounds := terrainLocalQueryBounds(shapeWorldAABB(primitive), terrainTransform)
	switch primitive.Type {
	case ShapeTypeSphere:
		return collideSphereTerrain(Sphere(primitive), terrain, terrainTransform, queryBounds)
	case ShapeTypeCapsule:
		return collideCapsuleTerrain(Capsule(primitive), terrain, terrainTransform, queryBounds)
	case ShapeTypeOOBB:
		return collideOOBBTerrain(OOBB(primitive), terrain, terrainTransform, queryBounds)
	default:
		return Contact{}, false
	}
}

func collideSphereSphere(a, b Sphere) (Contact, bool) {
	ab := b.Center.Subtract(a.Center)
	distSq := ab.LengthSquared()
	radius := a.Radius + b.Radius
	if distSq > radius*radius {
		return Contact{}, false
	}
	normal := matrix.Vec3Right()
	dist := matrix.Float(0)
	if distSq > contactEpsilon*contactEpsilon {
		dist = matrix.Sqrt(distSq)
		normal = ab.Scale(1 / dist)
	}
	pointA := a.Center.Add(normal.Scale(a.Radius))
	pointB := b.Center.Subtract(normal.Scale(b.Radius))
	return newContact(pointA, pointB, normal, radius-dist), true
}

func collideSphereMesh(s Sphere, mesh *MeshCollision, meshTransform *matrix.Transform) (Contact, bool) {
	if mesh == nil || len(mesh.Triangles) == 0 {
		return Contact{}, false
	}
	radiusSq := s.Radius * s.Radius
	bestDistanceSq := matrix.Inf(1)
	var bestContact Contact
	found := false
	mesh.ForEachWorldTriangle(meshTransform, func(tri DetailedTriangle) bool {
		closest := closestPointOnTriangle(s.Center, tri.Points[0], tri.Points[1], tri.Points[2])
		delta := closest.Subtract(s.Center)
		distSq := delta.LengthSquared()
		if distSq > radiusSq || distSq >= bestDistanceSq {
			return true
		}
		normal := primitiveToTriangleNormal(s.Center, closest, tri)
		dist := matrix.Float(0)
		if distSq > contactEpsilon*contactEpsilon {
			dist = matrix.Sqrt(distSq)
			normal = delta.Scale(1 / dist)
		}
		pointA := s.Center.Add(normal.Scale(s.Radius))
		bestContact = newContact(pointA, closest, normal, s.Radius-dist)
		bestDistanceSq = distSq
		found = true
		return true
	})
	return bestContact, found
}

func collideSphereTerrain(s Sphere, terrain *TerrainCollision, terrainTransform *matrix.Transform, queryBounds AABB) (Contact, bool) {
	radiusSq := s.Radius * s.Radius
	bestDistanceSq := matrix.Inf(1)
	var bestContact Contact
	found := false
	forEachTerrainWorldTriangle(terrain, terrainTransform, queryBounds, func(tri DetailedTriangle) bool {
		closest := closestPointOnTriangle(s.Center, tri.Points[0], tri.Points[1], tri.Points[2])
		delta := closest.Subtract(s.Center)
		distSq := delta.LengthSquared()
		if distSq > radiusSq || distSq >= bestDistanceSq {
			return true
		}
		normal := primitiveToTriangleNormal(s.Center, closest, tri)
		dist := matrix.Float(0)
		if distSq > contactEpsilon*contactEpsilon {
			dist = matrix.Sqrt(distSq)
			normal = delta.Scale(1 / dist)
		}
		pointA := s.Center.Add(normal.Scale(s.Radius))
		bestContact = newContact(pointA, closest, normal, s.Radius-dist)
		bestDistanceSq = distSq
		found = true
		return true
	})
	return bestContact, found
}

func collideSphereAABB(s Sphere, b AABB) (Contact, bool) {
	min := b.Min()
	max := b.Max()
	closest := clampVec3(s.Center, min, max)
	delta := closest.Subtract(s.Center)
	distSq := delta.LengthSquared()
	if distSq > s.Radius*s.Radius {
		return Contact{}, false
	}
	if distSq > contactEpsilon*contactEpsilon {
		dist := matrix.Sqrt(distSq)
		normal := delta.Scale(1 / dist)
		pointA := s.Center.Add(normal.Scale(s.Radius))
		return newContact(pointA, closest, normal, s.Radius-dist), true
	}
	normal, faceDistance := closestAABBFaceNormal(s.Center, b)
	pointA := s.Center.Add(normal.Scale(s.Radius))
	pointB := s.Center.Add(normal.Scale(faceDistance))
	return newContact(pointA, pointB, normal, s.Radius+faceDistance), true
}

func collideSphereOOBB(s Sphere, b OOBB) (Contact, bool) {
	localCenter := b.Orientation.Transpose().MultiplyVec3(s.Center.Subtract(b.Center))
	localBox := NewAABB(matrix.Vec3Zero(), b.Extent)
	localSphere := NewSphere(localCenter, s.Radius)
	contact, ok := collideSphereAABB(localSphere, localBox)
	if !ok {
		return Contact{}, false
	}
	contact.PointA = b.Orientation.MultiplyVec3(contact.PointA).Add(b.Center)
	contact.PointB = b.Orientation.MultiplyVec3(contact.PointB).Add(b.Center)
	contact.Point = contact.PointA.Add(contact.PointB).Scale(0.5)
	contact.Normal = safeNormal(b.Orientation.MultiplyVec3(contact.Normal), fallbackNormal(s.Center, b.Center))
	return contact, true
}

func collideSphereCapsule(s Sphere, c Capsule) (Contact, bool) {
	a, b := capsuleSegment(c)
	closest := closestPointOnSegment(s.Center, a, b)
	virtual := Sphere{
		Center: closest,
		Radius: c.Radius,
		Type:   ShapeTypeSphere,
	}
	return collideSphereSphere(s, virtual)
}

func collideSphereCylinder(s Sphere, c Cylinder) (Contact, bool) {
	direction := safeNormal(c.Direction, matrix.Vec3Up())
	halfHeight := c.Height * 0.5
	diff := s.Center.Subtract(c.Center)
	height := matrix.Vec3Dot(diff, direction)
	radial := diff.Subtract(direction.Scale(height))
	radialLength := radial.Length()
	radialNormal := safeNormal(radial, direction.Orthogonal())
	absHeight := matrix.Abs(height)
	insideHeight := absHeight <= halfHeight
	insideRadius := radialLength <= c.Radius
	if insideHeight && insideRadius {
		sideExit := c.Radius - radialLength
		capExit := halfHeight - absHeight
		normal := radialNormal
		pointB := c.Center.Add(direction.Scale(height)).Add(radialNormal.Scale(c.Radius))
		exitDistance := sideExit
		if capExit <= sideExit {
			sign := matrix.Float(1)
			if height < 0 {
				sign = -1
			}
			normal = direction.Scale(sign)
			pointB = c.Center.Add(direction.Scale(sign * halfHeight)).Add(radial)
			exitDistance = capExit
		}
		pointA := s.Center.Add(normal.Scale(s.Radius))
		return newContact(pointA, pointB, normal, s.Radius+exitDistance), true
	}
	clampedHeight := klib.Clamp(height, -halfHeight, halfHeight)
	clampedRadius := radialLength
	if clampedRadius > c.Radius {
		clampedRadius = c.Radius
	}
	closest := c.Center.Add(direction.Scale(clampedHeight)).Add(radialNormal.Scale(clampedRadius))
	delta := closest.Subtract(s.Center)
	distanceSq := delta.LengthSquared()
	if distanceSq > s.Radius*s.Radius {
		return Contact{}, false
	}
	distance := matrix.Float(0)
	normal := fallbackNormal(s.Center, c.Center)
	if distanceSq > contactEpsilon*contactEpsilon {
		distance = matrix.Sqrt(distanceSq)
		normal = delta.Scale(1 / distance)
	}
	pointA := s.Center.Add(normal.Scale(s.Radius))
	return newContact(pointA, closest, normal, s.Radius-distance), true
}

func collideSphereCone(s Sphere, c Cone) (Contact, bool) {
	closest, distance, inside := closestPointOnConeSurface(s.Center, c)
	delta := closest.Subtract(s.Center)
	distanceSq := delta.LengthSquared()
	if !inside && distanceSq > s.Radius*s.Radius {
		return Contact{}, false
	}
	normal := safeNormal(delta, fallbackNormal(s.Center, c.Center))
	if !inside && distanceSq > contactEpsilon*contactEpsilon {
		distance = matrix.Sqrt(distanceSq)
	}
	penetration := s.Radius - distance
	if inside {
		penetration = s.Radius + distance
	}
	pointA := s.Center.Add(normal.Scale(s.Radius))
	return newContact(pointA, closest, normal, penetration), true
}

func collideCylinderOOBB(c Cylinder, b OOBB) (Contact, bool) {
	direction := safeNormal(c.Direction, matrix.Vec3Up())
	axes := [8]matrix.Vec3{}
	axisCount := 0
	addAxis := func(axis matrix.Vec3) {
		if axis.LengthSquared() <= contactEpsilon*contactEpsilon {
			return
		}
		axes[axisCount] = axis
		axisCount++
	}
	addAxis(direction)
	for i := 0; i < 3; i++ {
		boxAxis := b.Orientation.ColumnVector(i)
		addAxis(boxAxis)
		addAxis(matrix.Vec3Cross(direction, boxAxis))
	}
	centerDelta := b.Center.Subtract(c.Center)
	radialDelta := centerDelta.Subtract(direction.Scale(matrix.Vec3Dot(centerDelta, direction)))
	addAxis(radialDelta)
	normal := matrix.Vec3Right()
	minOverlap := matrix.Inf(1)
	for i := 0; i < axisCount; i++ {
		axis := safeNormal(axes[i], matrix.Vec3Right())
		cRadius := projectCylinderRadius(c, axis)
		bRadius := projectOOBBRadius(b, axis)
		centerDistance := matrix.Vec3Dot(centerDelta, axis)
		overlap := cRadius + bRadius - matrix.Abs(centerDistance)
		if overlap < 0 {
			return Contact{}, false
		}
		if overlap < minOverlap {
			minOverlap = overlap
			if centerDistance < 0 {
				axis = axis.Negative()
			}
			normal = axis
		}
	}
	pointA := supportCylinder(c, normal)
	pointB := supportOOBB(b, normal.Negative())
	return newContact(pointA, pointB, normal, minOverlap), true
}

func collideConeOOBB(c Cone, b OOBB) (Contact, bool) {
	direction := safeNormal(c.Direction, matrix.Vec3Up())
	axes := [9]matrix.Vec3{}
	axisCount := 0
	addAxis := func(axis matrix.Vec3) {
		if axis.LengthSquared() <= contactEpsilon*contactEpsilon {
			return
		}
		axes[axisCount] = axis
		axisCount++
	}
	addAxis(direction)
	centerDelta := b.Center.Subtract(c.Center)
	radialDelta := centerDelta.Subtract(direction.Scale(matrix.Vec3Dot(centerDelta, direction)))
	if radialDelta.LengthSquared() > contactEpsilon*contactEpsilon {
		sideAxis := radialDelta.Normal().Scale(c.Height).Subtract(direction.Scale(c.Radius))
		addAxis(sideAxis)
		addAxis(radialDelta)
	}
	for i := 0; i < 3; i++ {
		boxAxis := b.Orientation.ColumnVector(i)
		addAxis(boxAxis)
		addAxis(matrix.Vec3Cross(direction, boxAxis))
	}
	normal := matrix.Vec3Right()
	minOverlap := matrix.Inf(1)
	for i := 0; i < axisCount; i++ {
		axis := safeNormal(axes[i], matrix.Vec3Right())
		coneMin, coneMax := projectCone(c, axis)
		boxCenter := matrix.Vec3Dot(b.Center, axis)
		boxRadius := projectOOBBRadius(b, axis)
		boxMin := boxCenter - boxRadius
		boxMax := boxCenter + boxRadius
		overlap := min(coneMax, boxMax) - max(coneMin, boxMin)
		if overlap < 0 {
			return Contact{}, false
		}
		if overlap < minOverlap {
			minOverlap = overlap
			if matrix.Vec3Dot(centerDelta, axis) < 0 {
				axis = axis.Negative()
			}
			normal = axis
		}
	}
	pointA := supportCone(c, normal)
	pointB := supportOOBB(b, normal.Negative())
	return newContact(pointA, pointB, normal, minOverlap), true
}

func collideCapsuleMesh(c Capsule, mesh *MeshCollision, meshTransform *matrix.Transform) (Contact, bool) {
	if mesh == nil || len(mesh.Triangles) == 0 {
		return Contact{}, false
	}
	a, b := capsuleSegment(c)
	radiusSq := c.Radius * c.Radius
	bestDistanceSq := matrix.Inf(1)
	var bestContact Contact
	found := false
	mesh.ForEachWorldTriangle(meshTransform, func(tri DetailedTriangle) bool {
		segPoint, triPoint := closestSegmentTriangle(a, b, tri.Points[0], tri.Points[1], tri.Points[2])
		delta := triPoint.Subtract(segPoint)
		distSq := delta.LengthSquared()
		if distSq > radiusSq || distSq >= bestDistanceSq {
			return true
		}
		normal := primitiveToTriangleNormal(segPoint, triPoint, tri)
		dist := matrix.Float(0)
		if distSq > contactEpsilon*contactEpsilon {
			dist = matrix.Sqrt(distSq)
			normal = delta.Scale(1 / dist)
		}
		pointA := segPoint.Add(normal.Scale(c.Radius))
		bestContact = newContact(pointA, triPoint, normal, c.Radius-dist)
		bestDistanceSq = distSq
		found = true
		return true
	})
	return bestContact, found
}

func collideCapsuleTerrain(c Capsule, terrain *TerrainCollision, terrainTransform *matrix.Transform, queryBounds AABB) (Contact, bool) {
	a, b := capsuleSegment(c)
	radiusSq := c.Radius * c.Radius
	bestDistanceSq := matrix.Inf(1)
	var bestContact Contact
	found := false
	forEachTerrainWorldTriangle(terrain, terrainTransform, queryBounds, func(tri DetailedTriangle) bool {
		segPoint, triPoint := closestSegmentTriangle(a, b, tri.Points[0], tri.Points[1], tri.Points[2])
		delta := triPoint.Subtract(segPoint)
		distSq := delta.LengthSquared()
		if distSq > radiusSq || distSq >= bestDistanceSq {
			return true
		}
		normal := primitiveToTriangleNormal(segPoint, triPoint, tri)
		dist := matrix.Float(0)
		if distSq > contactEpsilon*contactEpsilon {
			dist = matrix.Sqrt(distSq)
			normal = delta.Scale(1 / dist)
		}
		pointA := segPoint.Add(normal.Scale(c.Radius))
		bestContact = newContact(pointA, triPoint, normal, c.Radius-dist)
		bestDistanceSq = distSq
		found = true
		return true
	})
	return bestContact, found
}

func collideAABBAABB(a, b AABB) (Contact, bool) {
	delta := b.Center.Subtract(a.Center)
	overlap := a.Extent.Add(b.Extent).Subtract(delta.Abs())
	if overlap.X() < 0 || overlap.Y() < 0 || overlap.Z() < 0 {
		return Contact{}, false
	}
	axis := overlap.LongestAxis()
	penetration := overlap[axis]
	if overlap.X() <= overlap.Y() && overlap.X() <= overlap.Z() {
		axis = matrix.Vx
		penetration = overlap.X()
	} else if overlap.Y() <= overlap.Z() {
		axis = matrix.Vy
		penetration = overlap.Y()
	}
	normal := matrix.Vec3Zero()
	normal[axis] = 1
	if delta[axis] < 0 {
		normal[axis] = -1
	}
	min := matrix.Vec3Max(a.Min(), b.Min())
	max := matrix.Vec3Min(a.Max(), b.Max())
	point := min.Add(max).Scale(0.5)
	pointA := point
	pointB := point
	pointA[axis] = a.Center[axis] + normal[axis]*a.Extent[axis]
	pointB[axis] = b.Center[axis] - normal[axis]*b.Extent[axis]
	return newContact(pointA, pointB, normal, penetration), true
}

func collideOOBBOOBB(a, b OOBB) (Contact, bool) {
	normal := matrix.Vec3Right()
	minOverlap := matrix.Inf(1)
	centerDelta := b.Center.Subtract(a.Center)
	for i := 0; i < 3; i++ {
		if !satBoxAxis(a, b, a.Orientation.ColumnVector(i), centerDelta, &normal, &minOverlap) {
			return Contact{}, false
		}
		if !satBoxAxis(a, b, b.Orientation.ColumnVector(i), centerDelta, &normal, &minOverlap) {
			return Contact{}, false
		}
	}
	for i := 0; i < 3; i++ {
		for j := 0; j < 3; j++ {
			axis := matrix.Vec3Cross(a.Orientation.ColumnVector(i), b.Orientation.ColumnVector(j))
			if axis.LengthSquared() <= contactEpsilon*contactEpsilon {
				continue
			}
			if !satBoxAxis(a, b, axis, centerDelta, &normal, &minOverlap) {
				return Contact{}, false
			}
		}
	}
	pointA := supportOOBB(a, normal)
	pointB := supportOOBB(b, normal.Negative())
	return newContact(pointA, pointB, normal, minOverlap), true
}

func collideOOBBMesh(box OOBB, mesh *MeshCollision, meshTransform *matrix.Transform) (Contact, bool) {
	if mesh == nil || len(mesh.Triangles) == 0 {
		return Contact{}, false
	}
	bestPenetration := matrix.Inf(1)
	var bestContact Contact
	found := false
	mesh.ForEachWorldTriangle(meshTransform, func(tri DetailedTriangle) bool {
		contact, ok := collideOOBBTriangle(box, tri)
		if !ok || contact.Penetration >= bestPenetration {
			return true
		}
		bestPenetration = contact.Penetration
		bestContact = contact
		found = true
		return true
	})
	return bestContact, found
}

func collideOOBBTerrain(box OOBB, terrain *TerrainCollision, terrainTransform *matrix.Transform, queryBounds AABB) (Contact, bool) {
	bestPenetration := matrix.Inf(1)
	var bestContact Contact
	found := false
	forEachTerrainWorldTriangle(terrain, terrainTransform, queryBounds, func(tri DetailedTriangle) bool {
		contact, ok := collideOOBBTriangle(box, tri)
		if !ok || contact.Penetration >= bestPenetration {
			return true
		}
		bestPenetration = contact.Penetration
		bestContact = contact
		found = true
		return true
	})
	return bestContact, found
}

func collideOOBBTriangle(box OOBB, tri DetailedTriangle) (Contact, bool) {
	normal := matrix.Vec3Right()
	minOverlap := matrix.Inf(1)
	triPoints := tri.Points
	axes := [13]matrix.Vec3{}
	axes[0] = box.Orientation.ColumnVector(0)
	axes[1] = box.Orientation.ColumnVector(1)
	axes[2] = box.Orientation.ColumnVector(2)
	axes[3] = triangleNormal(tri)
	edge0 := triPoints[1].Subtract(triPoints[0])
	edge1 := triPoints[2].Subtract(triPoints[1])
	edge2 := triPoints[0].Subtract(triPoints[2])
	edges := [3]matrix.Vec3{edge0, edge1, edge2}
	index := 4
	for i := 0; i < 3; i++ {
		boxAxis := box.Orientation.ColumnVector(i)
		for j := 0; j < 3; j++ {
			axes[index] = matrix.Vec3Cross(boxAxis, edges[j])
			index++
		}
	}
	for i := range axes {
		axis := axes[i]
		if axis.LengthSquared() <= contactEpsilon*contactEpsilon {
			continue
		}
		axis = axis.Normal()
		if !satOOBBTriangleAxis(box, triPoints, axis, &normal, &minOverlap) {
			return Contact{}, false
		}
	}
	pointA := supportOOBB(box, normal)
	pointB := closestPointOnTriangle(pointA, triPoints[0], triPoints[1], triPoints[2])
	return newContact(pointA, pointB, normal, minOverlap), true
}

func collideCapsuleCapsule(a, b Capsule) (Contact, bool) {
	a0, a1 := capsuleSegment(a)
	b0, b1 := capsuleSegment(b)
	pa, pb := closestSegmentSegment(a0, a1, b0, b1)
	delta := pb.Subtract(pa)
	distSq := delta.LengthSquared()
	radius := a.Radius + b.Radius
	if distSq > radius*radius {
		return Contact{}, false
	}
	normal := fallbackNormal(a.Center, b.Center)
	dist := matrix.Float(0)
	if distSq > contactEpsilon*contactEpsilon {
		dist = matrix.Sqrt(distSq)
		normal = delta.Scale(1 / dist)
	}
	pointA := pa.Add(normal.Scale(a.Radius))
	pointB := pb.Subtract(normal.Scale(b.Radius))
	return newContact(pointA, pointB, normal, radius-dist), true
}

func collideCapsuleAABB(c Capsule, b AABB) (Contact, bool) {
	a0, a1 := capsuleSegment(c)
	t := closestSegmentAABBT(a0, a1, b)
	center := a0.Add(a1.Subtract(a0).Scale(t))
	virtual := Sphere{
		Center: center,
		Radius: c.Radius,
		Type:   ShapeTypeSphere,
	}
	return collideSphereAABB(virtual, b)
}

func collideCapsuleOOBB(c Capsule, b OOBB) (Contact, bool) {
	a0, a1 := capsuleSegment(c)
	inv := b.Orientation.Transpose()
	localA0 := inv.MultiplyVec3(a0.Subtract(b.Center))
	localA1 := inv.MultiplyVec3(a1.Subtract(b.Center))
	localCapsule := Capsule{
		Center:    localA0.Add(localA1).Scale(0.5),
		Radius:    c.Radius,
		Height:    localA0.Distance(localA1),
		Direction: safeNormal(localA1.Subtract(localA0), matrix.Vec3Up()),
		Type:      ShapeTypeCapsule,
	}
	contact, ok := collideCapsuleAABB(localCapsule, NewAABB(matrix.Vec3Zero(), b.Extent))
	if !ok {
		return Contact{}, false
	}
	contact.PointA = b.Orientation.MultiplyVec3(contact.PointA).Add(b.Center)
	contact.PointB = b.Orientation.MultiplyVec3(contact.PointB).Add(b.Center)
	contact.Point = contact.PointA.Add(contact.PointB).Scale(0.5)
	contact.Normal = safeNormal(b.Orientation.MultiplyVec3(contact.Normal), fallbackNormal(c.Center, b.Center))
	return contact, true
}

func newContact(pointA, pointB, normal matrix.Vec3, penetration matrix.Float) Contact {
	return Contact{
		Point:       pointA.Add(pointB).Scale(0.5),
		PointA:      pointA,
		PointB:      pointB,
		Normal:      safeNormal(normal, matrix.Vec3Right()),
		Penetration: max(penetration, 0),
	}
}

func flipContact(c Contact) Contact {
	c.BodyA, c.BodyB = c.BodyB, c.BodyA
	c.PointA, c.PointB = c.PointB, c.PointA
	c.Normal = c.Normal.Negative()
	return c
}

func approximateContact(a, b Shape) Contact {
	boundsA := shapeWorldAABB(a)
	boundsB := shapeWorldAABB(b)
	normal := fallbackNormal(boundsA.Center, boundsB.Center)
	pointA := supportAABB(boundsA, normal)
	pointB := supportAABB(boundsB, normal.Negative())
	penetration := approximatePenetration(boundsA, boundsB, normal)
	return newContact(pointA, pointB, normal, penetration)
}

func approximatePenetration(a, b AABB, normal matrix.Vec3) matrix.Float {
	axis := matrix.Vec3Abs(normal).LongestAxis()
	delta := matrix.Abs(b.Center[axis] - a.Center[axis])
	return max(a.Extent[axis]+b.Extent[axis]-delta, 0)
}

func worldShape(body *RigidBody) Shape {
	shape := body.Collision.Shape
	wm := body.Transform.WorldMatrix()
	scale := matrix.Vec3Abs(body.Transform.WorldScale())
	maxScale := scale.LongestAxisValue()
	if maxScale <= contactEpsilon {
		maxScale = 1
	}
	switch shape.Type {
	case ShapeTypeSphere:
		shape.Center = wm.TransformPoint(shape.Center)
		shape.Radius *= maxScale
	case ShapeTypeAABB:
		box := AABB(shape).Transform(wm)
		shape = Shape(box)
	case ShapeTypeOOBB:
		shape.Center = wm.TransformPoint(shape.Center)
		shape.Extent = shape.Extent.Multiply(scale)
		shape.Orientation = orthonormalMat3(wm)
	case ShapeTypeCapsule, ShapeTypeCylinder, ShapeTypeCone:
		shape.Center = wm.TransformPoint(shape.Center)
		shape.Radius *= maxScale
		shape.Height *= maxScale
		shape.Direction = transformDirection(wm, shape.Direction)
	case ShapeTypeMesh:
		box := AABB(shape).Transform(wm)
		shape.Center = box.Center
		shape.Extent = box.Extent
	}
	return shape
}

func shapeWorldAABB(shape Shape) AABB {
	switch shape.Type {
	case ShapeTypeSphere:
		extent := matrix.NewVec3XYZ(shape.Radius)
		return NewAABB(shape.Center, extent)
	case ShapeTypeAABB:
		return AABB(shape)
	case ShapeTypeOOBB:
		return OOBB(shape).Bounds()
	case ShapeTypeCapsule:
		a, b := capsuleSegment(Capsule(shape))
		extent := matrix.NewVec3XYZ(shape.Radius)
		return AABBFromMinMax(matrix.Vec3Min(a, b).Subtract(extent), matrix.Vec3Max(a, b).Add(extent))
	case ShapeTypeCylinder, ShapeTypeCone:
		radius := matrix.Sqrt(shape.Radius*shape.Radius + shape.Height*shape.Height*0.25)
		return NewAABB(shape.Center, matrix.NewVec3XYZ(radius))
	case ShapeTypeMesh:
		return NewAABB(shape.Center, shape.Extent)
	case ShapeTypeTerrain:
		return NewAABB(shape.Center, shape.Extent)
	default:
		return NullAABB
	}
}

func terrainLocalQueryBounds(worldBounds AABB, terrainTransform *matrix.Transform) AABB {
	localBounds := worldBounds
	if terrainTransform != nil {
		localBounds = worldBounds.Transform(terrainTransform.InverseWorldMatrix())
	}
	localBounds.Extent = localBounds.Extent.Add(matrix.NewVec3XYZ(contactEpsilon))
	return localBounds
}

func forEachTerrainWorldTriangle(terrain *TerrainCollision, terrainTransform *matrix.Transform, localBounds AABB, visit func(DetailedTriangle) bool) {
	if terrain == nil || visit == nil {
		return
	}
	minX, minZ, maxX, maxZ, ok := terrain.CellRangeForLocalAABB(localBounds)
	if !ok {
		return
	}
	var wm matrix.Mat4
	hasTransform := terrainTransform != nil
	if hasTransform {
		wm = terrainTransform.WorldMatrix()
	}
	for z := minZ; z <= maxZ; z++ {
		for x := minX; x <= maxX; x++ {
			p0 := terrain.GridToLocal(matrix.Float(x), matrix.Float(z))
			p1 := terrain.GridToLocal(matrix.Float(x), matrix.Float(z+1))
			p2 := terrain.GridToLocal(matrix.Float(x+1), matrix.Float(z+1))
			p3 := terrain.GridToLocal(matrix.Float(x+1), matrix.Float(z))
			if !visitTerrainTriangle([3]matrix.Vec3{p0, p1, p2}, wm, hasTransform, visit) {
				return
			}
			if !visitTerrainTriangle([3]matrix.Vec3{p0, p2, p3}, wm, hasTransform, visit) {
				return
			}
		}
	}
}

func visitTerrainTriangle(points [3]matrix.Vec3, wm matrix.Mat4, hasTransform bool, visit func(DetailedTriangle) bool) bool {
	if hasTransform {
		points = [3]matrix.Vec3{
			wm.TransformPoint(points[0]),
			wm.TransformPoint(points[1]),
			wm.TransformPoint(points[2]),
		}
	}
	return visit(DetailedTriangleFromPoints(points))
}

func satBoxAxis(a, b OOBB, axis, centerDelta matrix.Vec3, normal *matrix.Vec3, minOverlap *matrix.Float) bool {
	axis = safeNormal(axis, matrix.Vec3Right())
	ra := projectOOBBRadius(a, axis)
	rb := projectOOBBRadius(b, axis)
	centerDistance := matrix.Vec3Dot(centerDelta, axis)
	overlap := ra + rb - matrix.Abs(centerDistance)
	if overlap < 0 {
		return false
	}
	if overlap < *minOverlap {
		*minOverlap = overlap
		if centerDistance < 0 {
			axis = axis.Negative()
		}
		*normal = axis
	}
	return true
}

func satOOBBTriangleAxis(box OOBB, points [3]matrix.Vec3, axis matrix.Vec3, normal *matrix.Vec3, minOverlap *matrix.Float) bool {
	boxCenter := matrix.Vec3Dot(box.Center, axis)
	boxRadius := projectOOBBRadius(box, axis)
	boxMin := boxCenter - boxRadius
	boxMax := boxCenter + boxRadius
	triMin := matrix.Vec3Dot(points[0], axis)
	triMax := triMin
	for i := 1; i < 3; i++ {
		projection := matrix.Vec3Dot(points[i], axis)
		triMin = min(triMin, projection)
		triMax = max(triMax, projection)
	}
	overlap := min(boxMax, triMax) - max(boxMin, triMin)
	if triMax-triMin <= contactEpsilon {
		overlap = boxRadius - matrix.Abs(triMin-boxCenter)
	}
	if overlap < 0 {
		return false
	}
	if overlap < *minOverlap {
		if matrix.Vec3Dot(points[0].Subtract(box.Center), axis) < 0 {
			axis = axis.Negative()
		}
		*normal = axis
		*minOverlap = overlap
	}
	return true
}

func projectOOBBRadius(box OOBB, axis matrix.Vec3) matrix.Float {
	return matrix.Abs(matrix.Vec3Dot(box.Orientation.ColumnVector(0), axis))*box.Extent.X() +
		matrix.Abs(matrix.Vec3Dot(box.Orientation.ColumnVector(1), axis))*box.Extent.Y() +
		matrix.Abs(matrix.Vec3Dot(box.Orientation.ColumnVector(2), axis))*box.Extent.Z()
}

func supportOOBB(box OOBB, direction matrix.Vec3) matrix.Vec3 {
	point := box.Center
	for i := 0; i < 3; i++ {
		axis := box.Orientation.ColumnVector(i)
		sign := matrix.Float(1)
		if matrix.Vec3Dot(axis, direction) < 0 {
			sign = -1
		}
		point = point.Add(axis.Scale(sign * box.Extent[i]))
	}
	return point
}

func supportCylinder(c Cylinder, direction matrix.Vec3) matrix.Vec3 {
	axis := safeNormal(c.Direction, matrix.Vec3Up())
	point := c.Center
	if matrix.Vec3Dot(direction, axis) >= 0 {
		point = point.Add(axis.Scale(c.Height * 0.5))
	} else {
		point = point.Subtract(axis.Scale(c.Height * 0.5))
	}
	radial := direction.Subtract(axis.Scale(matrix.Vec3Dot(direction, axis)))
	if radial.LengthSquared() > contactEpsilon*contactEpsilon {
		point = point.Add(radial.Normal().Scale(c.Radius))
	}
	return point
}

func supportCone(c Cone, direction matrix.Vec3) matrix.Vec3 {
	axis := safeNormal(c.Direction, matrix.Vec3Up())
	halfHeight := c.Height * 0.5
	apex := c.Center.Subtract(axis.Scale(halfHeight))
	base := c.Center.Add(axis.Scale(halfHeight))
	radial := direction.Subtract(axis.Scale(matrix.Vec3Dot(direction, axis)))
	if radial.LengthSquared() > contactEpsilon*contactEpsilon {
		base = base.Add(radial.Normal().Scale(c.Radius))
	}
	if matrix.Vec3Dot(base, direction) > matrix.Vec3Dot(apex, direction) {
		return base
	}
	return apex
}

func supportAABB(box AABB, direction matrix.Vec3) matrix.Vec3 {
	point := box.Center
	for i := 0; i < 3; i++ {
		if direction[i] >= 0 {
			point[i] += box.Extent[i]
		} else {
			point[i] -= box.Extent[i]
		}
	}
	return point
}

func projectCylinderRadius(c Cylinder, axis matrix.Vec3) matrix.Float {
	direction := safeNormal(c.Direction, matrix.Vec3Up())
	axisDot := matrix.Vec3Dot(axis, direction)
	radialSq := max(1-axisDot*axisDot, 0)
	return c.Height*0.5*matrix.Abs(axisDot) + c.Radius*matrix.Sqrt(radialSq)
}

func projectCone(c Cone, axis matrix.Vec3) (matrix.Float, matrix.Float) {
	maxPoint := supportCone(c, axis)
	minPoint := supportCone(c, axis.Negative())
	minProjection := matrix.Vec3Dot(minPoint, axis)
	maxProjection := matrix.Vec3Dot(maxPoint, axis)
	if minProjection > maxProjection {
		minProjection, maxProjection = maxProjection, minProjection
	}
	return minProjection, maxProjection
}

func closestPointOnConeSurface(point matrix.Vec3, c Cone) (matrix.Vec3, matrix.Float, bool) {
	axis := safeNormal(c.Direction, matrix.Vec3Up())
	height := max(c.Height, contactEpsilon)
	apex := c.Center.Subtract(axis.Scale(height * 0.5))
	local := point.Subtract(apex)
	axial := matrix.Vec3Dot(local, axis)
	radial := local.Subtract(axis.Scale(axial))
	radialLength := radial.Length()
	radialNormal := safeNormal(radial, axis.Orthogonal())
	sideT := klib.Clamp((axial*height+radialLength*c.Radius)/(height*height+c.Radius*c.Radius), 0, 1)
	sideAxial := sideT * height
	sideRadius := sideT * c.Radius
	sidePoint := apex.Add(axis.Scale(sideAxial)).Add(radialNormal.Scale(sideRadius))
	sideDistanceSq := (axial-sideAxial)*(axial-sideAxial) + (radialLength-sideRadius)*(radialLength-sideRadius)
	baseAxial := height
	baseRadius := klib.Clamp(radialLength, 0, c.Radius)
	basePoint := apex.Add(axis.Scale(baseAxial)).Add(radialNormal.Scale(baseRadius))
	baseDistanceSq := (axial-baseAxial)*(axial-baseAxial) + (radialLength-baseRadius)*(radialLength-baseRadius)
	closest := sidePoint
	distanceSq := sideDistanceSq
	if baseDistanceSq < distanceSq {
		closest = basePoint
		distanceSq = baseDistanceSq
	}
	inside := pointInCone(point, c)
	return closest, matrix.Sqrt(max(distanceSq, 0)), inside
}

func closestPointOnTriangle(point, a, b, c matrix.Vec3) matrix.Vec3 {
	ab := b.Subtract(a)
	ac := c.Subtract(a)
	ap := point.Subtract(a)
	d1 := ab.Dot(ap)
	d2 := ac.Dot(ap)
	if d1 <= 0 && d2 <= 0 {
		return a
	}
	bp := point.Subtract(b)
	d3 := ab.Dot(bp)
	d4 := ac.Dot(bp)
	if d3 >= 0 && d4 <= d3 {
		return b
	}
	vc := d1*d4 - d3*d2
	if vc <= 0 && d1 >= 0 && d3 <= 0 {
		v := d1 / (d1 - d3)
		return a.Add(ab.Scale(v))
	}
	cp := point.Subtract(c)
	d5 := ab.Dot(cp)
	d6 := ac.Dot(cp)
	if d6 >= 0 && d5 <= d6 {
		return c
	}
	vb := d5*d2 - d1*d6
	if vb <= 0 && d2 >= 0 && d6 <= 0 {
		w := d2 / (d2 - d6)
		return a.Add(ac.Scale(w))
	}
	va := d3*d6 - d5*d4
	if va <= 0 && (d4-d3) >= 0 && (d5-d6) >= 0 {
		w := (d4 - d3) / ((d4 - d3) + (d5 - d6))
		return b.Add(c.Subtract(b).Scale(w))
	}
	denom := 1 / (va + vb + vc)
	v := vb * denom
	w := vc * denom
	return a.Add(ab.Scale(v)).Add(ac.Scale(w))
}

func closestSegmentTriangle(p, q, a, b, c matrix.Vec3) (matrix.Vec3, matrix.Vec3) {
	if hit, ok := segmentTrianglePoint(p, q, a, b, c); ok {
		return hit, hit
	}
	bestSegment := p
	bestTriangle := closestPointOnTriangle(p, a, b, c)
	bestDistanceSq := bestSegment.Subtract(bestTriangle).LengthSquared()
	candidates := [1][2]matrix.Vec3{
		{q, closestPointOnTriangle(q, a, b, c)},
	}
	for i := range candidates {
		distanceSq := candidates[i][0].Subtract(candidates[i][1]).LengthSquared()
		if distanceSq < bestDistanceSq {
			bestSegment = candidates[i][0]
			bestTriangle = candidates[i][1]
			bestDistanceSq = distanceSq
		}
	}
	edges := [3][2]matrix.Vec3{{a, b}, {b, c}, {c, a}}
	for i := range edges {
		segPoint, edgePoint := closestSegmentSegment(p, q, edges[i][0], edges[i][1])
		distanceSq := segPoint.Subtract(edgePoint).LengthSquared()
		if distanceSq < bestDistanceSq {
			bestSegment = segPoint
			bestTriangle = edgePoint
			bestDistanceSq = distanceSq
		}
	}
	return bestSegment, bestTriangle
}

func segmentTrianglePoint(p, q, a, b, c matrix.Vec3) (matrix.Vec3, bool) {
	normal := matrix.Vec3Cross(b.Subtract(a), c.Subtract(a))
	direction := q.Subtract(p)
	denom := normal.Dot(direction)
	if matrix.Abs(denom) <= contactEpsilon {
		return matrix.Vec3Zero(), false
	}
	t := normal.Dot(a.Subtract(p)) / denom
	if t < 0 || t > 1 {
		return matrix.Vec3Zero(), false
	}
	point := p.Add(direction.Scale(t))
	if !pointInTriangle(point, a, b, c) {
		return matrix.Vec3Zero(), false
	}
	return point, true
}

func pointInTriangle(point, a, b, c matrix.Vec3) bool {
	v0 := c.Subtract(a)
	v1 := b.Subtract(a)
	v2 := point.Subtract(a)
	dot00 := v0.Dot(v0)
	dot01 := v0.Dot(v1)
	dot02 := v0.Dot(v2)
	dot11 := v1.Dot(v1)
	dot12 := v1.Dot(v2)
	denom := dot00*dot11 - dot01*dot01
	if matrix.Abs(denom) <= contactEpsilon {
		return false
	}
	invDenom := 1 / denom
	u := (dot11*dot02 - dot01*dot12) * invDenom
	v := (dot00*dot12 - dot01*dot02) * invDenom
	return u >= -contactEpsilon && v >= -contactEpsilon && u+v <= 1+contactEpsilon
}

func primitiveToTriangleNormal(primitivePoint, trianglePoint matrix.Vec3, tri DetailedTriangle) matrix.Vec3 {
	delta := trianglePoint.Subtract(primitivePoint)
	if delta.LengthSquared() > contactEpsilon*contactEpsilon {
		return delta.Normal()
	}
	normal := triangleNormal(tri)
	if normal.Dot(primitivePoint.Subtract(trianglePoint)) > 0 {
		normal = normal.Negative()
	}
	return safeNormal(normal, fallbackNormal(primitivePoint, tri.Centroid))
}

func triangleNormal(tri DetailedTriangle) matrix.Vec3 {
	normal := matrix.Vec3Cross(
		tri.Points[1].Subtract(tri.Points[0]),
		tri.Points[2].Subtract(tri.Points[0]),
	)
	return safeNormal(normal, tri.Normal)
}

func closestAABBFaceNormal(point matrix.Vec3, box AABB) (matrix.Vec3, matrix.Float) {
	minimum := box.Min()
	maximum := box.Max()
	bestAxis := matrix.Vx
	bestSign := matrix.Float(-1)
	bestDistance := point.X() - minimum.X()
	if d := maximum.X() - point.X(); d < bestDistance {
		bestDistance = d
		bestSign = 1
	}
	if d := point.Y() - minimum.Y(); d < bestDistance {
		bestDistance = d
		bestAxis = matrix.Vy
		bestSign = -1
	}
	if d := maximum.Y() - point.Y(); d < bestDistance {
		bestDistance = d
		bestAxis = matrix.Vy
		bestSign = 1
	}
	if d := point.Z() - minimum.Z(); d < bestDistance {
		bestDistance = d
		bestAxis = matrix.Vz
		bestSign = -1
	}
	if d := maximum.Z() - point.Z(); d < bestDistance {
		bestDistance = d
		bestAxis = matrix.Vz
		bestSign = 1
	}
	normal := matrix.Vec3Zero()
	normal[bestAxis] = bestSign
	return normal, max(bestDistance, 0)
}

func closestPointOnSegment(point, a, b matrix.Vec3) matrix.Vec3 {
	ab := b.Subtract(a)
	denom := ab.LengthSquared()
	if denom <= contactEpsilon*contactEpsilon {
		return a
	}
	t := matrix.Vec3Dot(point.Subtract(a), ab) / denom
	t = klib.Clamp(t, 0, 1)
	return a.Add(ab.Scale(t))
}

func closestSegmentAABBT(a, b matrix.Vec3, box AABB) matrix.Float {
	left := matrix.Float(0)
	right := matrix.Float(1)
	segment := b.Subtract(a)
	for range 12 {
		m1 := left + (right-left)/3
		m2 := right - (right-left)/3
		p1 := a.Add(segment.Scale(m1))
		p2 := a.Add(segment.Scale(m2))
		d1 := pointAABBDistanceSquared(p1, box)
		d2 := pointAABBDistanceSquared(p2, box)
		if d1 < d2 {
			right = m2
		} else {
			left = m1
		}
	}
	return (left + right) * 0.5
}

func pointAABBDistanceSquared(point matrix.Vec3, box AABB) matrix.Float {
	closest := clampVec3(point, box.Min(), box.Max())
	return point.Subtract(closest).LengthSquared()
}

func closestSegmentSegment(p1, q1, p2, q2 matrix.Vec3) (matrix.Vec3, matrix.Vec3) {
	d1 := q1.Subtract(p1)
	d2 := q2.Subtract(p2)
	r := p1.Subtract(p2)
	a := d1.Dot(d1)
	e := d2.Dot(d2)
	f := d2.Dot(r)
	s := matrix.Float(0)
	t := matrix.Float(0)
	if a <= contactEpsilon && e <= contactEpsilon {
		return p1, p2
	}
	if a <= contactEpsilon {
		t = klib.Clamp(f/e, 0, 1)
	} else {
		c := d1.Dot(r)
		if e <= contactEpsilon {
			s = klib.Clamp(-c/a, 0, 1)
		} else {
			b := d1.Dot(d2)
			denom := a*e - b*b
			if denom != 0 {
				s = klib.Clamp((b*f-c*e)/denom, 0, 1)
			}
			t = (b*s + f) / e
			if t < 0 {
				t = 0
				s = klib.Clamp(-c/a, 0, 1)
			} else if t > 1 {
				t = 1
				s = klib.Clamp((b-c)/a, 0, 1)
			}
		}
	}
	return p1.Add(d1.Scale(s)), p2.Add(d2.Scale(t))
}

func capsuleSegment(c Capsule) (matrix.Vec3, matrix.Vec3) {
	direction := safeNormal(c.Direction, matrix.Vec3Up())
	half := c.Height * 0.5
	return c.Center.Subtract(direction.Scale(half)), c.Center.Add(direction.Scale(half))
}

func clampVec3(point, min, max matrix.Vec3) matrix.Vec3 {
	return matrix.NewVec3(
		klib.Clamp(point.X(), min.X(), max.X()),
		klib.Clamp(point.Y(), min.Y(), max.Y()),
		klib.Clamp(point.Z(), min.Z(), max.Z()),
	)
}

func fallbackNormal(from, to matrix.Vec3) matrix.Vec3 {
	return safeNormal(to.Subtract(from), matrix.Vec3Right())
}

func safeNormal(v, fallback matrix.Vec3) matrix.Vec3 {
	if v.LengthSquared() <= contactEpsilon*contactEpsilon {
		if fallback.LengthSquared() <= contactEpsilon*contactEpsilon {
			return matrix.Vec3Right()
		}
		return fallback.Normal()
	}
	return v.Normal()
}

func transformDirection(m matrix.Mat4, direction matrix.Vec3) matrix.Vec3 {
	if direction.LengthSquared() <= contactEpsilon*contactEpsilon {
		direction = matrix.Vec3Up()
	}
	rot := orthonormalMat3(m)
	return safeNormal(rot.MultiplyVec3(direction), matrix.Vec3Up())
}

func orthonormalMat3(m matrix.Mat4) matrix.Mat3 {
	right := safeNormal(m.Right(), matrix.Vec3Right())
	up := safeNormal(m.Up(), matrix.Vec3Up())
	forward := safeNormal(m.Forward(), matrix.Vec3Forward())
	return matrix.Mat3{
		right.X(), up.X(), forward.X(),
		right.Y(), up.Y(), forward.Y(),
		right.Z(), up.Z(), forward.Z(),
	}
}
