/******************************************************************************/
/* editor_plugin_registry.go                                                  */
/******************************************************************************/
/* MIT License, Copyright (c) 2015-present Brent Farris, (John 4:13-14)       */
/******************************************************************************/

// Code generated by editor_plugin package; DO NOT EDIT.

package main
