name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: kaijuengine.org
          #EXTRA_PACKAGES: build-base
          #REQUIREMENTS: folder/requirements.txt
